config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  get 'landing_page/index'
  root 'landing_page#index'
  get 'users/profile' => 'users#profile'
  get 'galleries' => 'galleries#index'
  get 'likes/new' => 'likes#new'
  get 'likes/create' => 'likes#create'
  get 'likes/index' =>'likes#index'

  resources :properties
  resources :likes	
  resources :mensajes
  resources :reservacions
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/arrendador.rb
class Arrendador < ApplicationRecord
  belongs_to :usuario
  has_many :property
  has_many :reservation
  has_many :mensaje
end

app/models/arrendatario.rb
class Arrendatario < ApplicationRecord
  belongs_to :usuario
  has_many :likes
  has_many :reservation
  has_many :mensaje
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :property
  belongs_to :arrendatario

  validates_uniqueness_of :propiedad_id, :scope => [:arrendatario_id]
end

app/models/mensaje.rb
class Mensaje < ApplicationRecord
	belongs_to :arrendador
   	belongs_to :arrendatario
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :arrendador
  validates :title, presence:true,length:{minimum:5}
	validates :description, presence:true,length:{minimum:5}	
	has_attached_file :image, :styles => {
      :thumb => "100x100#",
      :small  => "150x150#",
      :medium => "200x200#" }, default_url: "/images/:style/missing.png"
	
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/	
end

app/models/reservacion.rb
class Reservacion < ApplicationRecord
	belongs_to :arrendador
   	belongs_to :arrendatario
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :registraRolUsuario

  def registraRolUsuario
  	 if(self.rol == 'Arrendador')
  	 	a1 = Arrendador.new({usuario_id: self.id,numprop: 0})
  	 	a1.save()
  	 elsif (self.rol == 'Arrendatario')
  	 	a1 = Arrendatario.new({usuario_id: self.id,numrentas: 0,universidad: 'ITAM'})
  	 	a1.save()
  	 end
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
	before_action :authenticate_usuario!
	before_action :permiso_arrendatario
	def index
		if (current_usuario!=nil)
			@arrId = Arrendatario.where(usuario_id:current_usuario.id).first.id
		end
		@properties = Property.all()
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :authenticate_usuario!
	before_action :permiso_arrendatario
	skip_before_filter  :verify_authenticity_token

	def index
		@likes = Like.all()
	end

	def show
		@like = Like.find(params[:id])
	end

	def new
		if(current_usuario!=nil)
			@like = Like.new
		end

	end

	def create
		if(current_usuario!=nil)
			@like = Like.new(like_params)
			@like.save
		end
	end

	def edit
		@like = Like.find(params[:id])
	end

	def update
		@like = Like.find(params[:id])
		if(@like.update(property_params))
			redirect_to @like
		else
			render 'edit'
		end
	end

	def destroy
		@like = Like.find(params[:id])
		@like.destroy
		redirect_to likes_path
	end

	private def like_params
		params.require(:like).permit(:data,:propiedad_id,:arrendatario_id)
	end
end

app/controllers/mensajes_controller.rb
class MensajesController < ApplicationController
	before_action :authenticate_usuario!
	def index
		@mensajes = Mensaje.all()
	end

	def show
		@mensaje = Mensaje.find(params[:id])
	end

	def new
		@usuarios = Usuario.where.not(id: current_usuario.id)
		@mensaje = Mensaje.new
	end

	def create
		if(current_usuario!=nil)
			if(current_usuario.rol == 'Arrendador')
				arr = Arrendador.where(usuario_id:current_usuario.id).first
			else
				arr = Arrendatario.where(usuario_id:current_usuario.id).first
			end
			id2 = dameIdArrUsr(params[:mens][:usr].to_i)
			if(current_usuario.rol == 'Arrendador')
				tipo = {id_arrendador: arr.id,id_arrendatario: id2}

			else
				tipo = {id_arrendatario: arr.id,id_arrendador: id2}
			end
			@mensaje = Mensaje.new(mensaje_params.merge(tipo))
			if(@mensaje.save)
				redirect_to @mensaje
			else
				render 'new'
			end
		end
	end

	def edit
		@mensaje = Mensaje.find(params[:id])

	end

	def update
		@mensaje = Mensaje.find(params[:id])
		if(@mensaje.update(mensaje_params))
			redirect_to @mensaje
		else
			render 'edit'
		end
	end

	def destroy
		@mensaje = Mensaje.find(params[:id])
		@mensaje.destroy
		redirect_to mensajes_path
	end

	private def mensaje_params
		
		params.require(:mens).permit(:titulo,:horaEnvio,:mensaje)
	end
	private def dameIdArrUsr(idUsr)
		if(current_usuario!= nil && !current_usuario.blank?)
      		rol = Usuario.find(idUsr).rol
      		if (rol == 'Arrendador')
      			return Arrendador.where(usuario_id:idUsr).first.id
      		else
      			return Arrendatario.where(usuario_id:idUsr).first.id
      		end
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index
		@properties = Property.all()
	end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
		before_action :authenticate_usuario!

	before_action :permiso_arrendador
	

	def index
		@properties = Property.all()

	end

	def show
		@property = Property.find(params[:id])
	end

	def new
		@property = Property.new
	end

	def create
		#render plain: params[:property].inspect
		if(current_usuario!=nil)
			arr = Arrendador.where(usuario_id:current_usuario.id).first
			@property = Property.new(property_params.merge(arrendador_id: arr.id))
			if(@property.save)
				redirect_to @property
			else
				render 'new'
			end
		end
	end

	def edit
		@property = Property.find(params[:id])

	end

	def update
		@property = Property.find(params[:id])
		if(@property.update(property_params))
			redirect_to @property
		else
			render 'edit'
		end
	end

	def destroy
		@property = Property.find(params[:id])
		@property.destroy
		redirect_to properties_path
	end

	private def property_params
		
		params.require(:property).permit(:title,:price,:description,:image)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_usuario!
	def profile

	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/mensajes_helper.rb
module MensajesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/reservacions_helper.rb
module ReservacionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/likes/index.html.erb
<%= button_to('Explorar', galleries_path, method: :get , class: "btn btn-default btn-lg")%>

</br>
<h3>Favoritos</h3>


<div class="container centradito">

<% @likes.each do |like| %>
<div class="well">
  <p>Título de la propiedad: <%= Property.find(like.propiedad_id).title %></p>
  <p>Precio: $<%= Property.find(like.propiedad_id).price %></p>
  <p>Arrendador: <%= Usuario.find(Arrendador.find(Property.find(like.propiedad_id).arrendador_id).usuario_id).email %></p>
  <p>Descripción: <%= Property.find(like.propiedad_id).description%></p>
  <%= button_to('Contactar a propietario', new_mensaje_path, method: :get , class: "btn btn-default btn-lg")%>
  </br>
  <%= link_to "Eliminar", like_path(like),method: :delete, data: {confirm: 'Estas seguro?'}, :class => 'btn btn-danger' %>
</div>

<% end %>	
</div>

app/views/mensajes/index.html.erb
<h3>Bandeja de entrada</h3>
<div class="container centradito">

</br>
<% @mensajes.each do |mensaje| %>
<div class="well">
  <h4><%= mensaje.titulo %></h4>
  <p><%= mensaje.mensaje %></p>
  <%= link_to "Más información", mensaje_path(mensaje), :class => 'btn btn-default' %>
  </br>
  </br>
  <p><%= mensaje.created_at %></p>
  
  <%= button_to('Responder', new_mensaje_path, method: :get , class: "btn btn-primary btn-med ")%>

  </div>
</div>

<% end %>	

</div>

app/views/mensajes/new.html.erb
<h3>Enviar un mensaje</h3>

<div class="container centradito">

<%= form_for :mens, url: mensajes_path do |f| %>
	<% if @mensaje.errors.any? %>
		<% @mensaje.errors.full_messages.each do |msg| %>
			<div class = "alert alert-danger"><%= msg %></div>
			<% end %>
		<% end %>
	</br>
	<p>
	<%= f.label :usr, 'Usuario a contactar' %><br>
	<%= f.select :usr, @usuarios.collect {|p| [ p.nombre, p.id ] } %>
	</p>	

	
	<p>
		<%= f.label :titulo, 'Título' %><br>
		<%= f.text_field(:titulo, {:class => 'form-control'}) %>
	</p>
	<p>
		<%= f.label :mensaje, 'Descripción' %><br>
		<%= f.text_area(:mensaje,{:class => 'form-control'})%>
	</p>
	<%= f.submit({value:'Enviar', :class => 'btn btn-primary'}) %>
<% end %>

</div>

app/views/mensajes/show.html.erb
<div class="container centradito">


<h2><%= @mensaje.titulo %></h2>
<p><%= @mensaje.mensaje %></p>
<hr>
<%= button_to('Enviar un nuevo mensaje', new_mensaje_path, method: :get , class: "btn btn-default btn-lg")%>
</hr>
<hr>
<%= link_to "Eliminar", mensaje_path(@mensaje),method: :delete, data: {confirm: 'Estas seguro?'}, :class => 'btn btn-danger' %>
<hr>
</div>

app/views/properties/edit.html.erb
<div class="container centradito">

<h1>Edita propiedad</h1>
<%= form_for :property, url: property_path(@property), method: :patch do |f| %>
	<% if @property.errors.any? %>
		<% @property.errors.full_messages.each do |msg| %>
			<div class = "alert alert-danger"><%= msg %></div>
			<% end %>
		<% end %>
		

	<p>
		<%= f.label :title %><br>
		<%= f.text_field(:title, {:class => 'form-control'}) %>
	</p>
	<p>
		<%= f.label :price %><br>
		<%= f.number_field(:price, {:class => 'form-control'}) %>
	</p>
	<p>
		<%= f.label :description%><br>
		<%= f.text_area(:description,{:class => 'form-control'})%>
	</p>

	<p>
		<%= f.submit({:class => 'btn btn-primary'}) %>
	</p>
<% end %>

</div>

app/views/properties/index.html.erb
<div class="container centradito">

<%= button_to('Agregar propiedad', new_property_path, method: :get , class: "btn btn-default btn-lg")%>
</br>
<h1>Propiedades</h1>
<% @properties.each do |property| %>
<div class="well">
  <h3><%= property.title %></h3>
  <p><%= property.description %></p>
  <%= link_to "Más información", property_path(property), :class => 'btn btn-default' %>
</div>
<% end %>
</div>	

app/views/properties/new.html.erb
<div class="container centradito">

<h1>Agregar una propiedad</h1>
<%= form_for :property, url: properties_path, html:{multipart:true} do |f| %>
	<% if @property.errors.any? %>
		<% @property.errors.full_messages.each do |msg| %>
			<div class = "alert alert-danger"><%= msg %></div>
			<% end %>
		<% end %>
		
	<p>
		<%= f.label :title, 'Título' %><br>
		<%= f.text_field(:title, {:class => 'form-control'}) %>
	</p>
	<p>
		<%= f.label :price, 'Precio' %><br>
		<%= f.number_field(:price) %>
	</p>
	<p>
		<%= f.label :description, 'Descripción' %><br>
		<%= f.text_area(:description,{:class => 'form-control'})%>
	</p>
	<p>
		<%= f.label :image, 'Imagen' %><br>
		<%= f.file_field(:image) %>
	</p>

	<p>
		<%= f.submit({value:'Agregar propiedad', :class => 'btn btn-primary'}) %>
		<%= @currentArrendatarioId %>
	</p>
<% end %>
</div>

app/views/properties/show.html.erb
<div class="container centradito">

<%= button_to('Ver mis propiedaes', properties_path, method: :get , class: "btn btn-default btn-lg")%>
</br>

<h2><%= @property.title %></h2>

<%= image_tag @property.image.url(:medium)%>


<p><%= @property.description %></p>


<hr>

<%= link_to "Editar", edit_property_path(@property), :class => 'btn btn-default' %>
<%= link_to "Eliminar", property_path(@property),method: :delete, data: {confirm: 'Estas seguro?'}, :class => 'btn btn-danger' %>
<hr>
</div>