config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  get 'landing_page/index'
  root 'landing_page#index'
  get 'users/profile' => 'users#profile'
  get 'galleries' => 'galleries#index'
  get 'likes/new' => 'likes#new'
  get 'likes/create' => 'likes#create'
  get 'likes/index' =>'likes#index'

  resources :properties
  resources :likes	
  resources :mensajes
  resources :reservacions
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/arrendador.rb
class Arrendador < ApplicationRecord
  belongs_to :usuario
  has_many :property
  has_many :reservation
  has_many :mensaje
end

app/models/arrendatario.rb
class Arrendatario < ApplicationRecord
  belongs_to :usuario
  has_many :likes
  has_many :reservation
  has_many :mensaje
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :property
  belongs_to :arrendatario

  validates_uniqueness_of :propiedad_id, :scope => [:arrendatario_id]
end

app/models/mensaje.rb
class Mensaje < ApplicationRecord
	belongs_to :arrendador
   	belongs_to :arrendatario
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :arrendador
  validates :title, presence:true,length:{minimum:5}
	validates :description, presence:true,length:{minimum:5}	
	has_attached_file :image, :styles => {
      :thumb => "100x100#",
      :small  => "150x150#",
      :medium => "200x200#" }, default_url: "/images/:style/missing.png"
	
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/	
end

app/models/reservacion.rb
class Reservacion < ApplicationRecord
	belongs_to :arrendador
   	belongs_to :arrendatario
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :registraRolUsuario

  def registraRolUsuario
  	 if(self.rol == 'Arrendador')
  	 	a1 = Arrendador.new({usuario_id: self.id,numprop: 0})
  	 	a1.save()
  	 elsif (self.rol == 'Arrendatario')
  	 	a1 = Arrendatario.new({usuario_id: self.id,numrentas: 0,universidad: 'ITAM'})
  	 	a1.save()
  	 end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :authenticate_usuario!
	before_action :permiso_arrendatario
	skip_before_filter  :verify_authenticity_token

	def index
		@likes = Like.all()
	end

	def show
		@like = Like.find(params[:id])
	end

	def new
		if(current_usuario!=nil)
			@like = Like.new
		end

	end

	def create
		if(current_usuario!=nil)
			@like = Like.new(like_params)
			@like.save
		end
	end

	def edit
		@like = Like.find(params[:id])
	end

	def update
		@like = Like.find(params[:id])
		if(@like.update(property_params))
			redirect_to @like
		else
			render 'edit'
		end
	end

	def destroy
		@like = Like.find(params[:id])
		@like.destroy
		redirect_to likes_path
	end

	private def like_params
		params.require(:like).permit(:data,:propiedad_id,:arrendatario_id)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index
		@properties = Property.all()
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_usuario!
	def profile

	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/mensajes_helper.rb
module MensajesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/reservacions_helper.rb
module ReservacionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <link href="https://fonts.googleapis.com/css?family=Lato:100,200,300,400,500,600,700" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,200,300,400,500,600,700" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
  
    <title>Ohana</title>
    <%= favicon_link_tag 'ohana_favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', params[:controller], media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', params[:controller], 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-spy="scroll" data-target="#navbar-collapse-1" data-offset="70">
    <nav class="navbar navbar-default navbar-fixed-top menuOhana">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header logo">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to (image_tag("ohana_logo.png", :alt => "logo Ohana", :class => "logoHead")), root_path, :class => "navbar-header" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right ulNav">
            <li id="liInicio"> <%= link_to 'Inicio', root_path, id: "linkInicio" %> </li>
            <li id="liQue"> <%= link_to '¿Qué es Ohana?', root_path + "#que", id: "linkQue" %> </li>
            <li id="liComo"> <%= link_to '¿Cómo funciona Ohana?', root_path + "#como", id: "linkComo" %> </li>
            <% if rol_usuario == 'Arrendatario' %>
                <li> <%= link_to "Explorar", galleries_path %></li>
            <% end %>

            <% if usuario_signed_in? %>
                  <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hola, <%= current_usuario.nombre+'  '%><span class="caret"></span></a>
                <ul class="dropdown-menu">
                <li><%= link_to('Mi perfil', users_profile_path, :method => :get) %></li>
                  <li><%= link_to('Editar mi perfil', edit_usuario_registration_path, :method => :get) %></li>
                  <li role="separator" class="divider"></li>
                    <li><%= link_to('Cerrar sesión', destroy_usuario_session_path, :method => :delete) %></li>
                  </ul>
                  
                  </ul>
                <% else %>
                  <li>
                  <%= link_to('Iniciar sesión', new_usuario_session_path)  %>  
                  </li>
                  <li>
                  <%= link_to('Crear cuenta', new_usuario_registration_path)  %>
                  </li>
            <% end %>


          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <%if current_page?(root_path) %>
      <%= yield %>
    <% else %>
      <div class="container-fluid centradito">
          <%= yield %>
      </div>
    <% end %> 
  </body>

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->

  <script src="http://hammerjs.github.io/dist/hammer-time.min.js"></script>

</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<h3><%= @content %></h3>

app/views/partials/_fav.html.erb
	<h3>Información sobre favoritos</h3>
	</br>
	<%= button_to('Ver mis favoritos', likes_path, method: :get , class: "btn btn-default btn-lg")%>
	</br>

app/views/partials/_info.html.erb
	<h3>Datos personales</h3>
	</br>
	<h4>Nombre: </h4><h4><%= current_usuario.nombre%></h4>
	</br>
	<h4>Apellidos: </h4><h4><%= current_usuario.apellido%></h4>
	</br>
	<h4>eMail: </h4><h4><%= current_usuario.email%></h4>
	</br>
	<h4>Rol de usuario: </h4><h4><%= current_usuario.rol%></h4>

app/views/partials/_msgs.html.erb
	<h3>Información sobre mensajes</h3>
	</br>
	<%= button_to('Ver mis mensajes', mensajes_path, method: :get , class: "btn btn-default btn-lg")%>
	</br>
	<%= button_to('Enviar un nuevo mensaje', new_mensaje_path, method: :get , class: "btn btn-default btn-lg")%>

app/views/partials/_prop.html.erb
	<h3>Información sobre mis propiedades</h3>
	</br>
	<%= button_to('Ver mis propiedaes', properties_path, method: :get , class: "btn btn-default btn-lg")%>
	</br>
	<%= button_to('Agregar propiedad', new_property_path, method: :get , class: "btn btn-default btn-lg")%>

app/views/partials/_res.html.erb
	<h3>Información sobre reservaciones</h3>
	</br>
	<%= button_to('Ver mis reservaciones', reservacions_path, method: :get , class: "btn btn-default btn-lg")%>
	